name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [develop]

jobs:
  build:
    # Job name is Greeting
    name: Greeting nr 3
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Update version in pom.xml
        run: cd /home/runner/work | pwd