name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [develop]

jobs:
  publish:
    # Job name is Greeting
    name: Greeting nr 3
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Update version in pom.xml
        run: mvn clean