name: Bump up version
on:
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Bump up version
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Update version in pom.xml
        run: mvn -B release:update-versions